#!/bin/sh -ue

# This script deploys a main or release version.
#
# See [README.md] for an explanation of this and how CI should use it.
version=${1:-main}

# Use implicit version when main, if we can..
if [ "${version}" = "main" ]; then
  version=$(sed -En 's/.*<version>(.*)<\/version>.*/\1/p' pom.xml| head -1)
fi

build-bin/maven/maven_deploy
export RELEASE_FROM_MAVEN_BUILD=true
build-bin/docker_push ${version}
